// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdnuinoitugxklgiaysi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkbnVpbm9pdHVneGtsZ2lheXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjE0OTIsImV4cCI6MjA2Mjc5NzQ5Mn0.CPfl5igbuW6r0Nk3Ydo_k3hOP26i4sS7b4xo45JNgys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);